version: "3.8"

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  app:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgresql:
  postgresql_data:
